### ISSUE TITLE
服务器版本

### ISSUE THREAD

**Issue by Dawn-Dream** [Dawn-Dream/Frustrated-World-Server#1]
1.15.2到1.16.1选择

**Comment by Dawn-Dream** [comment]
> 1.15.2到1.16.1选择

1.15.2有更好的插件体验与服务器优化
1.16    数据包有一点好处

**Comment by EmptyDust** [comment]
暂时用1.15.2吧，1.16确实优化查的离谱（之前我32g内存给1.16.1我的世界单人用了12g），但是如果后续1.16的优化变好的话，还是去1.16




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Dawn-Dream/Frustrated-World-Server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 晚上7:42
收件人:&nbsp;"Dawn-Dream/Frustrated-World-Server"<Frustrated-World-Server@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Dawn-Dream/Frustrated-World-Server] 服务器版本 (#1)





  
1.15.2到1.16.1选择
  
1.15.2有更好的插件体验与服务器优化
 1.16    数据包有一点好处

**Comment by Dawn-Dream** [comment]
1.15.2
